# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181022_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='hood_id',
            new_name='hood',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
